# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'charting-webapp/charting-webapp.csproj'
    feedsToUse: 'config'
    nugetConfigPath: 'charting-webapp/NuGet.config'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'charting-webapp/charting-webapp.csproj'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: DownloadBuildArtifacts@0
  inputs:
    buildType: 'current'
    downloadType: 'single'
    artifactName: 'drop'
    downloadPath: '$(System.ArtifactsDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Az400JulyHotmailAzureFreePassExpires190820'
    appType: 'webApp'
    WebAppName: 'chartin-webapp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    AppSettings: '-PROJECT charting-webapp/charting-webapp.csproj'


