# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master



stages:
- stage: Build

  jobs:
  - job: BuildWebApp
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      nugetFile: './NuGet.config'
      projectFile: 'charting-webapp/charting-webapp.csproj'
      System.Debug: true
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'
  
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'config'
        nugetConfigPath: $(nugetFile)

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build all web projects'
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish just function app!'
      inputs:
        command: publish
        publishWebProjects: false
        projects: '**/charting-functions.csproj'
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    # - task: ArchiveFiles@2
    #   displayName: 'Archive files'
    #   inputs:
    #     rootFolderOrFile: 'charting-functions'
    #     includeRootFolder: false
    #     archiveFile: '$(Build.ArtifactStagingDirectory)/OccupancyDataProcessorFn.zip'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish all web projects as separate zip'
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory)'
        zipAfterPublish: True

    - script: echo 'B'
    - task: PublishBuildArtifacts@1
      displayName: 'publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: DeployWebApp
  jobs:
  - job: Deploy
    pool: 
      vmImage: 'vs2017-win2016'
    variables:
      - group: GymOccupancyVG
    steps:
    - script: echo $(GymWebApiUrl)
    - task: DownloadBuildArtifacts@0
      displayName: 'download build artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.DefaultWorkingDirectory)'

    - task: AzureFunctionApp@1
      displayName: 'Azure Function App Deploy: gymoccupancy'
      inputs:
        azureSubscription: Az400JulyHotmailAzureFreePassExpires190820
        appType: functionApp
        appName: gymoccupancy   
        package: '$(System.DefaultWorkingDirectory)/**/OccupancyDataProcessorFn.zip'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure RM deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Az400JulyHotmailAzureFreePassExpires190820'
        appType: 'webApp'
        WebAppName: 'chartin-webapp'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/charting-webapp.zip'
        AppSettings: '-PROJECT charting-webapp/charting-webapp.csproj -Apis:gymwebapiurl $(GymWebApiUrl)'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure RM deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Az400JulyHotmailAzureFreePassExpires190820'
        appType: 'webApp'
        WebAppName: 'chartin-webapi'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/charting-webapi.zip'
        AppSettings: '-PROJECT charting-webapi/charting-webapi.csproj'

