# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master



stages:
- stage: Build
  variables:
    System.Debug: true
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
  jobs:
  - job: BuildWebApp
    pool:
      vmImage: 'vs2017-win2016'
    variables:
      nugetFile: 'charting-webapp/NuGet.config'
      projectFile: 'charting-webapp/charting-webapp.csproj'

  
    steps:
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        nugetConfigPath: $(nugetFile)

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        command: 'build'
        projects: 'gym-occupancy.sln'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(Build.ArtifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        projects: 'charting-webapp/charting-webapp.csproj'
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/webapp'
        zipAfterPublish: True
        - task: DotNetCoreCLI@2
        displayName: 'dotnet publish'
        inputs:
          projects: 'charting-webapi/charting-webapi.csproj'
          command: publish
          publishWebProjects: True
          arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/webapi'
          zipAfterPublish: True
          
    - script: echo 'B'
    - task: PublishBuildArtifacts@1
      displayName: 'publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        
 

- stage: DeployWebApp
  jobs:
  - job: Deploy
    pool: 
      vmImage: 'vs2017-win2016'
    variables:
      - group: GymOccupancyVG
    steps:
    - script: echo $(GymWebApiUrl)
    - task: DownloadBuildArtifacts@0
      displayName: 'download build artifact'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.DefaultWorkingDirectory)'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Azure RM deploy'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Az400JulyHotmailAzureFreePassExpires190820'
        appType: 'webApp'
        WebAppName: 'chartin-webapp'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
        AppSettings: '-PROJECT charting-webapp/charting-webapp.csproj -Apis:gymwebapiurl $(GymWebApiUrl)'


